### ISSUE TITLE
Create topnavigation bar

### ISSUE THREAD

**Issue by simondereuver** [simondereuver/TWUN13#10]
Create a navigation bar at top of the webpage.

Some features of the naviagtion bar
- [x] Scalability, rezising window should not affect the bar
- [x] Sticky navigation bar, it needs to follow if the user scrolls on the page
- [x] Button for side panel at top left, Add a Home button, Calender button, Login button (top right) (Add buttons in order of this line)

**Comment by McFluffen** [comment]
Implemented all the above. Will add routing to this
